services:
  tubearchivist:
    build:
      context: 
      dockerfile: Dockerfile
    container_name: tubearchivist
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_CON=redis://archivist-redis:6379/1
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.jeyamir.lab
      - TA_USERNAME=admin
      - TA_PASSWORD=changeme
      - ELASTIC_PASSWORD=changeme
      - TZ=Asia/Kuala_Lumpur
      - TA_COOKIES_FILE=/app/cache/youtube-cookies.txt
    volumes:
      - '/home/jeyamir/tubearchivist/media:/youtube'
      - '/home/jeyamir/tubearchivist/cache:/app/cache'
    depends_on:
      archivist-es:
        condition: service_started
      archivist-redis:
        condition: service_healthy
      pot-provider:
        condition: service_started
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.routers.ta-custom.rule=Host(`tubearchivist.jeyamir.lab`)
      - traefik.http.routers.ta-custom.entrypoints=http
      - traefik.http.services.ta-custom.loadbalancer.server.port=8000

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - '/home/jeyamir/tubearchivist/redis:/data'
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=changeme"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - '/home/jeyamir/tubearchivist/es:/usr/share/elasticsearch/data'
    expose:
      - "9200"

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: pot-provider
    restart: unless-stopped
    expose:
      - "4416"